Css custom properties
sitevision/envision pull request #158
Opened 2021-02-02 14:18 UTC by henrikekelof

2021-02-02 15:44 UTC, albinohrn requested changes
Ser bra ut det var några småfunderingar och lite städrequests. :)

2021-02-02 15:44 UTC, albinohrn commented on packages/envision/src/scss/feed.scss
> +   border: 1px solid css-var("element-background-color");
Det här funderar jag på. Vill vi verkligen ha borders som är samma färg som bakgrunden? Borde vara transparent/inställningsbart? Vet att det varit så tidigare men funderar på om det är önskvärt

2021-02-02 15:44 UTC, albinohrn commented on packages/envision/src/scss/feed.scss
> +      border-bottom: 1px solid css-var("element-background-color");
Samma sak här

2021-02-02 15:44 UTC, albinohrn commented on packages/envision/src/scss/feed.scss
> +   border-top: 1px solid css-var("element-background-color");
Även här?

2021-02-02 15:44 UTC, albinohrn commented on packages/envision/src/scss/form.scss
> +      background-color: css-var("element-background-color");
Är detta rätt färg för ett inputfält?

2021-02-02 15:44 UTC, albinohrn commented on packages/envision/src/scss/form.scss
> +      // height: calc(#{$spacing-x-small + $spacing-x-small + $form-input-line-height} + #{$border-width * 2});
Finns i versionshistoriken

2021-02-02 15:44 UTC, albinohrn commented on packages/envision/src/scss/form.scss
> +      height: calc(#{css-var("spacing-x-small")} * 2 + #{$form-input-line-height * 1em} + #{$border-width * 2});
Borde line-height och border-width vara variabler?

2021-02-02 15:44 UTC, albinohrn commented on packages/envision/src/scss/form.scss
> +         // background: linear-gradient($color-brand, $color-brand);
Ta bort

2021-02-02 15:44 UTC, albinohrn commented on packages/envision/src/scss/modal-dialog.scss
> +      //@include border-radius($radius-medium);
Bort

2021-02-02 15:44 UTC, albinohrn commented on packages/envision/src/scss/modal-dialog.scss
> +      //background-color: $color-brand;
Ta bort

2021-02-02 15:44 UTC, albinohrn commented on packages/envision/src/scss/modal-dialog.scss
> +         //color: $font-color-invert;
Ta bort

2021-02-02 15:44 UTC, albinohrn commented on packages/envision/src/scss/modal-dialog.scss
> +      //background-color: css-var("element-background-color");
Ta bort

2021-02-02 15:44 UTC, albinohrn commented on packages/envision/src/scss/tab.scss
> +      //background-color: $color-element-bg;
Ta bort

2021-02-02 19:41 UTC, albinohrn commented on packages/envision/src/scss/variable.scss
> +   "button-link-focus-border-color": css-var("focus-color"),
Jag hittar inte att `css-var("focus-color")` är definierad nånstans

2021-02-02 20:09 UTC, albinohrn commented on packages/envision/src/scss/variable.scss
> +   "collapse-border": $collapse-heading-border,
Här har vi slagit ihop allt till en border-property. I pagination t ex har vi behållit `border-width`, `border-style` osv. (Det passar lite bättre med den gamla konfigurationen. )

2021-02-03 15:24 UTC, henrikekelof commented on packages/envision-docs/src/pages/components/dropdown.md
> +      <svg class="env-icon env-icon--small env-icon--invert env-dropdown-icon">
Nej, den råkade följa med från POC:en. Tar bort.

2021-02-03 15:24 UTC, henrikekelof commented on packages/envision-docs/src/pages/utils/text.md
> +```html
Råkade följa med från POC:en. Tar bort.

2021-02-03 15:30 UTC, henrikekelof commented on packages/envision/src/scss/button.scss
> +   $buttonNames: "primary", "success", "danger", "invert", "link";
Inte nu, vi tar det i framtida ändringar.

2021-02-03 15:34 UTC, henrikekelof commented on packages/envision/src/scss/feed.scss
> +   border: 1px solid css-var("element-background-color");
Vi tar det i framtida förbättringsarbete: http://jira.sitevision.net/browse/ENV-14

2021-02-03 15:37 UTC, henrikekelof commented on packages/envision/src/scss/form.scss
> +      background-color: css-var("element-background-color");
Nja. Jag sätter den till "font-color-invert" så har vi inte ändrat något f.n. och tar med det i ENV-14-diskussionerna.

2021-02-03 15:41 UTC, henrikekelof commented on packages/envision/src/scss/form.scss
> +      // height: calc(#{$spacing-x-small + $spacing-x-small + $form-input-line-height} + #{$border-width * 2});
Städar!

2021-02-03 15:41 UTC, henrikekelof commented on packages/envision/src/scss/form.scss
> +      height: calc(#{css-var("spacing-x-small")} * 2 + #{$form-input-line-height * 1em} + #{$border-width * 2});
ENV-14

2021-02-05 07:55 UTC, albinohrn requested changes
En lite grej som jag kunde hitta. Sen finns det två konflikter också som måste lösas

2021-02-05 07:55 UTC, albinohrn commented on packages/envision-docs/src/pages/components/feed.md
> +               <button placeholder="Comment" type="button" class="env-button env-button--primary">
Vad används `placeholder` till på en `button`?

2021-02-05 12:59 UTC, albinohrn approved these changes

2021-02-16 09:38 UTC, merged