Block links
sitevision/envision pull request #204
Opened 2021-04-09 08:45 UTC by henrikekelof

2021-04-09 09:06 UTC, melineric requested changes
Ser bra ut, bara en liten dublett bara!

2021-04-09 09:06 UTC, melineric commented on packages/envision/src/scss/variable.scss
> +$block-secondary-border-color: #a7bed0;
Blev det en dublett här? :)

2021-04-09 15:28 UTC, henrikekelof commented on packages/envision/src/scss/variable.scss
> +$block-secondary-border-color: #a7bed0;
Ibland är det bra att deklarera en variabel flera gånger om inte första försöket lyckas.

2021-04-13 05:35 UTC, melineric approved these changes

2021-04-13 05:43 UTC, merged