changed default border radius for badge,alert
sitevision/envision pull request #220
Opened 2021-04-23 09:29 UTC by melineric

2021-04-26 12:02 UTC, JimmyRoselin commented
Border-radius kommer endast förändras via teman på webbplatsen via den specifika inställningen för respektive komponent. 

Vi vill ha en generell inställning också som är "back-up" om man inte satt något specifikt på en komponent/variabel.

Generella inställningen i gränssnittet kommer enklast skriva ett nytt värde till var(--env-border-radius), (sedan räknas small/medium/large om och respektive variabel sätts till nya värdet)

scss-variablerna ändras aldrig. Alerten kommer alltid att vara .125 och badgen 0.25 om man endast ändrar den generella inställningen för border-radius. (Som inte finns implementerad än, men snart).

Går att hantera vid rendering av temat i SV också genom att alltid skriva över de specifika radius-variablerna, men det blir nog onödigt trasslig logik för att få det att lira.

Använd css-varibeln istället för scss-variabeln. Detta behöver göras på övriga som använder sig av scss-variabeln, form-input + button. Kanske något mer?

2021-04-26 12:04 UTC, JimmyRoselin requested changes
Border-radius kommer endast förändras via teman på webbplatsen via den specifika inställningen för respektive komponent.

Vi vill ha en generell inställning också som är "back-up" om man inte satt något specifikt på en komponent/variabel.

Generella inställningen i gränssnittet kommer enklast skriva ett nytt värde till var(--env-border-radius), (sedan räknas small/medium/large om och respektive variabel sätts till nya värdet)

scss-variablerna ändras aldrig. Alerten kommer alltid att vara .125 och badgen 0.25 om man endast ändrar den generella inställningen för border-radius. (Som inte finns implementerad än, men snart).

Går att hantera vid rendering av temat i SV också genom att alltid skriva över de specifika radius-variablerna, men det blir nog onödigt trasslig logik för att få det att lira.

Använd css-varibeln istället för scss-variabeln. Detta behöver göras på övriga som använder sig av scss-variabeln, form-input + button. Kanske något mer?

2021-04-26 12:51 UTC, henrikekelof commented
Har inte hunnit kodgranska, men det som Jimmy skrev var tanken. Jag tänker mig en "master" som går att sätta till 0 och som då slår på alla andra. Så funkar "vanliga" border-radius-small o.s.v som utgår från base. Det skulle då kunna bli t.ex:
'badge-border-radius': css-var('border-radius-small'), 
(Eller vad som passar bäst)

2021-04-28 12:56 UTC, JimmyRoselin approved these changes

2021-04-29 06:50 UTC, merged