Env 79 tag select
sitevision/envision pull request #239
Opened 2021-05-27 12:46 UTC by henrikekelof

2021-05-27 13:07 UTC, albinohrn requested changes

2021-05-27 13:07 UTC, albinohrn commented on packages/envision/src/js/util/util.js
> +      cleanOptions(options, defaults) {
Kanske skulle vi fundera på att flytta denna till en egen util. Så att vi inte bara fortsätter bygga på den här slasktratten

2021-05-27 13:07 UTC, albinohrn commented on packages/envision/src/js/select.js
> +         select.clear();
Inte säker på att man vill göra `clear` här? Tänk scenariot att man söker mot en backend när man skriver, ska det funka? Då vill man byta ut valbara options men de valda ska fortfarande finnas kvar

2021-05-27 13:13 UTC, albinohrn commented on packages/envision/src/js/select.js
> +         select.clear();
Verkar som att man använder `options` för statisk data eller `load` för dynamisk. Så jag tror att vi skulle exponera `load` och ta bort `setOptions`

2021-05-27 13:18 UTC, albinohrn commented on packages/envision/src/js/select.js
> +            (this.el.tagName.toUpperCase() === 'SELECT' &&
Spara `this.el.tagName.toUpperCase()` i en variabel

2021-05-27 13:23 UTC, albinohrn commented
Saknar också möjlighet att översätta texterna som finns i komponenten

2021-05-31 08:24 UTC, henrikekelof commented on packages/envision/src/js/util/util.js
> +      cleanOptions(options, defaults) {
Jag städar lite i den här, tar bort jQuery och bryter ut CSS-relaterade till en egen util.

2021-06-01 09:06 UTC, albinohrn requested changes
En liten textändring

2021-06-01 09:06 UTC, albinohrn commented on packages/envision-docs/src/pages/components/select.md
> +      and will invoke the callback with the results once they are available.
will -> should

2021-06-03 13:22 UTC, albinohrn approved these changes

2021-06-04 08:27 UTC, merged