Env 252 image viewer 2
sitevision/envision pull request #395
Opened 2023-05-25 11:46 UTC by henrikekelof

2023-05-29 11:38 UTC, JimmyRoselin requested changes

2023-05-29 11:38 UTC, JimmyRoselin commented on packages/envision-docs/src/pages/components/image-viewer-2.md
> +TODO MER HÄR
mer?

2023-05-29 11:38 UTC, JimmyRoselin commented on packages/envision-docs/src/pages/components/image-viewer-2.md
> +title: Image viewer 2
Behöver badge med info om när det finns tillgängligt

2023-05-29 11:38 UTC, JimmyRoselin commented on packages/envision/src/scss/image-viewer-2.scss
Finns det några passande variabler istället för att använda #fff/#000?

2023-05-29 11:46 UTC, henrikekelof commented on packages/envision/src/scss/image-viewer-2.scss
Min tanke är att det alltid är mörk botten med vit text. Oberoende av tema. Därför gick jag på färgerna direkt.

2023-05-31 13:56 UTC, JimmyRoselin approved these changes

2023-06-08 12:16 UTC, merged