Env 27 dynamic fonts
sitevision/envision pull request #427
Opened 2024-02-13 14:19 UTC by henrikekelof

Dynamic font scaling based on container width

2024-02-14 13:26 UTC, JimmyRoselin approved these changes
Nice

2024-02-14 13:26 UTC, JimmyRoselin commented on packages/envision-docs/src/pages/utils/dynamic-font-size.md
> +      <div class="example-dynamic-font__resizeable"><!-- -->
```suggestion
      <div class="example-dynamic-font__resizeable">
```

2024-02-14 13:26 UTC, JimmyRoselin commented on packages/envision-docs/src/pages/utils/dynamic-font-size.md
> +      <div class="example-dynamic-font__resizeable"><!-- -->
```suggestion
      <div class="example-dynamic-font__resizeable">
```

2024-02-14 13:26 UTC, JimmyRoselin commented on packages/envision-docs/src/pages/utils/dynamic-font-size.md
> +      <div class="example-dynamic-font__resizeable"><!-- -->
```suggestion
      <div class="example-dynamic-font__resizeable">
```

2024-02-14 13:26 UTC, JimmyRoselin commented on packages/envision-docs/src/pages/utils/dynamic-font-size.md
> +      <div class="example-dynamic-font__resizeable"><!-- -->
```suggestion
      <div class="example-dynamic-font__resizeable">
```

2024-02-15 10:05 UTC, albinohrn requested changes

2024-02-15 10:05 UTC, albinohrn commented on packages/envision/src/scss/util/dynamic-font-size.scss
> +   --df-scale: 1.25;
Vi borde prefixa "publika" variabler med `--env` för att följa hur det ser ut i övrigt.

2024-02-15 10:05 UTC, albinohrn commented on packages/envision/src/scss/util/dynamic-font-size.scss
> +.env-dynamic-font-container {
Detta borde vi lyfta ut till en egen utility som är mer generell. Annars riskerar vi att den återanvänds för andra saker t ex container queries.

2024-02-16 14:55 UTC, JimmyRoselin commented on packages/envision-docs/src/pages/utils/dynamic-font-size.md
> +         <div class="env-container example-dynamic-container" data-name="tjena">
tjena

2024-02-20 08:16 UTC, merged