Env 291 forms
sitevision/envision pull request #435
Opened 2024-03-25 08:29 UTC by henrikekelof

2024-03-27 09:49 UTC, JimmyRoselin commented
Kikade igenom dokumentationen. Under Tooltip och Tag Select använder vi också forms och de nu gamla klasserna.

Dessa borde också uppdateras med nya. Gör vi det nu eller kanske vänta tills det är live i sitevision?

2024-03-27 09:54 UTC, henrikekelof commented
Jag funderade faktiskt på det. Om vi ändrar nu kan man inte hitta en fungerande variant att kopiera. Tror det är bättre att exempel utanför Form får vara som dom är tills nya sakerna är i prod.

2024-03-27 11:38 UTC, JimmyRoselin requested changes

2024-03-27 11:38 UTC, JimmyRoselin commented on packages/envision-docs/src/pages/components/form.md
> +Each form field combination of text label and form control should be wrapped in `.env-form-field` for consistent spacing.
Kanske kan vara något vagare här. Jag fick i alla fall uppfattningen om att klassen behövs snarare att den är frivillig om man vill ha spacing

2024-03-27 11:38 UTC, JimmyRoselin commented on packages/envision-docs/src/pages/components/form.md
> +### Form row & column
Då denna är beroende av env-form-field för att fungera så kan det bli lite fel med margin. Troligt om man endast har ett fält så vill man inte ha margin-bottom som läggs till av klassen. Liknande om man har flera fält så vill man troligt inte ha det på sista utan löser spacing på annat sätt.

Superenkelt att skriva över själv så inte hela världen, men om vi kan knepa ut något sätt att hantera det på hade det nog underlättat

2024-04-19 09:27 UTC, albinohrn approved these changes

2024-05-16 07:11 UTC, JimmyRoselin approved these changes

2024-05-20 06:44 UTC, merged